import type { Metadata } from "next";
import { Inter ,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import UserNavbar from "@/components/UserNavbar";

const poppins = Poppins({ weight : '500' , subsets : ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let isLoggedin = false
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={poppins.className}>
        {isLoggedin == true ? <UserNavbar/> : <Navbar/> }
       
        {children}
        <Footer />
      </body>
    </html>
  );
}
